version: '3.8'

services:
  review-service:
    image: truongikpk/bookstore-review-service:v1.0.0
    container_name: review-service
    ports:
      - "8087:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
