@host = http://localhost:8087
@bookId = 123e4567-e89b-12d3-a456-426614174000
@userId = 7c6e9c8a-2a3f-4c11-9f3c-6b4f5f4a1d11

### 1. Thêm đánh giá mới cho một cuốn sách
POST {{host}}/api/v1/reviews/book/add
Content-Type: application/json

{
  "bookId": "{{bookId}}",
  "userId": "{{userId}}",
  "rating": 5,
  "comment": "Sách rất hay và đáng đọc!",
  "userName": "Người Dùng Test"
}

### 2. Lấy danh sách đánh giá của một cuốn sách (có phân trang)
GET {{host}}/api/v1/reviews/book/{{bookId}}?page=0&size=10
Accept: application/json

### 3. Đếm tổng số đánh giá của một người dùng
GET {{host}}/api/v1/reviews/users/{{userId}}/count
Accept: application/json
