spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: bookstore-review-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  signerKey: "your-very-secret-key-that-should-be-long-enough-for-hs512-algorithm"
